const NAME = 'BLOGS';

const FETCH_ALL_BLOGS = {
  START: `@@${NAME}/FETCH_ALL_BLOGS/START`,
  SUCCEED: `@@${NAME}/FETCH_ALL_BLOGS/SUCCEED`,
  FAIL: `@@${NAME}/FETCH_ALL_BLOGS/FAIL`,
};

export { NAME, FETCH_ALL_BLOGS };
