const NAME = 'EMAIL';
const SEND_EMAIL = {
  START: `@@${NAME}/SEND_EMAIL/START`,
  SUCCEED: `@@${NAME}/SEND_EMAIL/SUCCEED`,
  FAIL: `@@${NAME}/SEND_EMAIL/FAIL`,
};

const COMPLETE_AND_RETURN = `@@${NAME}/COMPLETE_AND_RETURN`;

export { SEND_EMAIL, COMPLETE_AND_RETURN };
